name: Profile Auto Build

on:
  schedule:
    - cron: "0 20 * * *"   # 毎日 05:00 JST 実行（UTC基準）
    - cron: "0 21 * * 0"   # 週1回 Metrics 生成（JST 朝6時）
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kimura00001
          template: classic
          base: header, repositories, activity, community, metadata
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_ignored: css, scss, html
          plugin_languages_sections: most-used, recently-used
          plugin_achievements: yes
          plugin_repositories: yes

      - name: Checkout
        uses: actions/checkout@v4

      - name: Move metrics output
        run: |
          # lowlighter/metrics はカレントに github-metrics.svg を吐く
          mv github-metrics.svg ./github-metrics.svg || true

      - name: Commit metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github-metrics.svg"
          file_pattern: "github-metrics.svg"

  snake_and_graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Snake
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: kimura00001
          outputs: |
            dist/snake.svg

      # Activity Graph
      - name: Generate Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@master
        with:
          # 色はデフォルト（いじりたいなら inputs 参照）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_PATH: dist/activity-graph.svg
          AREA: true

      - name: Push artifacts to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  summary_cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: kimura00001
          # THEME は default / solarized / github 等。好みで変更可
          THEME: default
      - name: Commit cards
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update summary cards"
          file_pattern: "profile-summary-card-output/**"
